Table customers {
  customer_id int [pk]
  customer_name varchar
  country varchar [note: "Can be NULL"]
  signup_date date
  is_active boolean [note: "0 = inactive, 1 = active, NULL = unknown"]
}

Table products {
  product_id int [pk]
  product_name varchar
  category varchar [note: "Can be NULL"]
  price decimal
}

Table orders {
  order_id int [pk]
  customer_id int
  product_id int
  order_date date
  quantity int [note: "Can be NULL"]
  order_status varchar [note: "Completed, Cancelled, Returned, Pending, NULL"]
}

Ref: orders.customer_id > customers.customer_id
Ref: orders.product_id > products.product_id
